### ISSUE TITLE
Error during listening

### ISSUE THREAD

**Issue by NehatLi** [FalconOscuro/Helldivers-Voice-Stratagem#1]
When I trigger to launch a stratagem, I got this error:
![image](https://github.com/FalconOscuro/Helldivers-Voice-Stratagem/assets/52033137/98ca5426-5d2b-4d09-b19a-1b69299575e3)

**Comment by FalconOscuro** [comment]
Don't worry, that's just me being lazy, program should function perfectly fine.
Issue stems from me skipping a few steps in initializing the output window, should probably fix it in the next commit though.

**Comment by FalconOscuro** [comment]
Issue fixed in commit # a17e3fd.
